sqlldr userid=projet/projet control=Data_CSV/Marque.ctl log=Data_TMP/Marque.log bad=Data_TMP/Marque.bad discard=Data_TMP/Marque.discard skip=1
sqlldr userid=projet/projet control=Data_CSV/Team.ctl log=Data_TMP/Team.log bad=Data_TMP/Team.bad discard=Data_TMP/Team.discard skip=1
sqlldr userid=projet/projet control=Data_CSV/Modele_moto.ctl log=Data_TMP/Modele_moto.log bad=Data_TMP/Modele_moto.bad discard=Data_TMP/Modele_moto.discard skip=1
sqlldr userid=projet/projet control=Data_CSV/Pilote.ctl log=Data_TMP/Pilote.log bad=Data_TMP/Pilote.bad discard=Data_TMP/Pilote.discard skip=1
sqlldr userid=projet/projet control=Data_CSV/Championnat.ctl log=Data_TMP/Championnat.log bad=Data_TMP/Championnat.bad discard=Data_TMP/Championnat.discard skip=1
sqlldr userid=projet/projet control=Data_CSV/Circuit.ctl log=Data_TMP/Circuit.log bad=Data_TMP/Circuit.bad discard=Data_TMP/Circuit.discard skip=1
sqlldr userid=projet/projet control=Data_CSV/Course_vitesse.ctl log=Data_TMP/Course_vitesse.log bad=Data_TMP/Course_vitesse.bad discard=Data_TMP/Course_vitesse.discard skip=1
sqlldr userid=projet/projet control=Data_CSV/Contrat.ctl log=Data_TMP/Contrat.log bad=Data_TMP/Contrat.bad discard=Data_TMP/Contrat.discard skip=1
sqlldr userid=projet/projet control=Data_CSV/Participe.ctl log=Data_TMP/Participe.log bad=Data_TMP/Participe.bad discard=Data_TMP/Participe.discard skip=1
